name: flutter_hello_moor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dart
  cupertino_icons: ^1.0.3

  drift: ^1.5.0
  # moor: ^4.3.2
  rxdart: ^0.27.1
  intl: ^0.17.0

  # Also use the latest version.
  sqlite3_flutter_libs: ^0.5.0

  # Helper to find the database path on mobile
  path_provider: ^2.0.2
  path: ^1.8.0
  undo: ^1.4.0

  moor_db_viewer: ^4.0.0
  
  drift_db_viewer: ^1.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  drift_dev: ^1.5.2
  # moor_generator: ^4.6.0
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true